# This is a basic workflow to help you get started with Actions

name: Git Pull

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop, master, stable, hotfix ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: http://guinn.pythonanywhere.com/git/pull/?token=${{secrets.DEBUG_TOKEN}}
